spring:
    datasource:
        url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456


file:
#    file: E:/work/file/
    file: D:/work/file/
    url: http://localhost:8989/
